control_ventilation:
  description: "Control the Qstream ventilation system."
  fields:
    timer:
      description: "Duration in minutes for the timer."
      example: 60
    percentage:
      description: "Fan speed percentage."
      example: 70
