control_ventilation:
  description: "Control the Qstream Ventilation"
  fields:
    timer:
      description: "Duration in minutes"
      example: 60
    percentage:
      description: "Speed percentage (0-100%)"
      example: 70
